
services: 
    web:
        build: . 
        depends_on:
            - db
        ports:
            - "3000:3000"
        volumes:
            - .:/opt/app
    
    db:
        image: mongo
        expose: 
            - "27017"
        volumes:
            - mongodata:/data/db
        
    
    