version: '3'

services: 
    pokenode:
        build: . 
        depends_on:
            - data
        ports:
            - "3001:3001"
        volumes:
            - .:/opt/app  
    data:
        image: mongo
        expose: 
            - "27017"
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db
        
volumes:
    mongodata:


    
    